# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "urdf_files",
    srcs = [
        "smooth_step.obj",
        "stairs.urdf",
        "track.obj",
        "track.urdf",
        "box_ramp.mtl",
        "box_ramp.obj"
    ],
)
