# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "stairs",
    srcs = [
        "smooth_step.obj",
        "stairs.urdf",
    ],
)
