# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "ramp",
    srcs = [
        "spiral_ramp.obj",
        "spiral_ramp.urdf",
    ],
)
