name: Release

on:
    workflow_dispatch:
    release:
        types:
            - created

jobs:
    pi3hat_spine:
        name: "Add pi3hat spine to release assets"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v3

            - name: "Install dependencies"
              run: |
                  sudo apt install libncurses5

            - name: "Build the pi3hat spine"
              run: |
                  tools/bazelisk build --verbose_failures --config=pi64 //spines:pi3hat_spine

            - name: "Add the spine to release assets"
              uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ github.workspace }}/bazel-bin/spines/pi3hat_spine
